<?php

namespace Stimulsoft\Viewer;

class Toolbar extends \Stimulsoft\OptionsBase
{
	protected static $validFields = array(
		'_zoom' => array('', -1 => 'PageWidth', -2 => 'PageHeight'),
		'alignment' => array('Left','Center','Right','Default'),
		'autoHide' => 'boolean',
		'backgroundColor' => 'Stimulsoft\\Viewer\\Color',
		'borderColor' => 'Stimulsoft\\Viewer\\Color',
		'displayMode' => 'integer',
		'fontColor' => 'Stimulsoft\\Viewer\\Color',
		'fontFamily' => 'string',
		'menuAnimation' => 'boolean',
		'multiPageHeightCount' => 'integer',
		'multiPageWidthCount' => 'integer',
		'printDestination' => array('Default','Pdf','Direct','WithPreview'),
		'showAboutButton' => 'boolean',
		'showBookmarksButton' => 'boolean',
		'showButtonCaptions' => 'boolean',
		'showCurrentPageControl' => 'boolean',
		'showDesignButton' => 'boolean',
		'showEditorButton' => 'boolean',
		'showFindButton' => 'boolean',
		'showFirstPageButton' => 'boolean',
		'showFullScreenButton' => 'boolean',
		'showLastPageButton' => 'boolean',
		'showMenuMode' => array('Click','Hover'),
		'showNextPageButton' => 'boolean',
		'showOpenButton' => 'boolean',
		'showParametersButton' => 'boolean',
		'showPinToolbarButton' => 'boolean',
		'showPreviousPageButton' => 'boolean',
		'showPrintButton' => 'boolean',
		'showRefreshButton' => 'boolean',
		'showResourcesButton' => 'boolean',
		'showSaveButton' => 'boolean',
		'showSendEmailButton' => 'boolean',
		'showViewModeButton' => 'boolean',
		'showZoomButton' => 'boolean',
		'viewMode' => array('SinglePage','Continuous','MultiplePages','OnePage','WholeReport','MultiPage'),
		'visible' => 'boolean',
	);

	protected static $defaults = array(
		'_zoom' => 100,
		'alignment' => 3,
		'autoHide' => false,
		'backgroundColor' => array(
			'name' => 'Empty',
			'_a' => 0,
			'_r' => 255,
			'_g' => 255,
			'_b' => 255,
		),
		'borderColor' => array(
			'name' => 'Empty',
			'_a' => 0,
			'_r' => 255,
			'_g' => 255,
			'_b' => 255,
		),
		'displayMode' => 0,
		'fontColor' => array(
			'name' => 'Empty',
			'_a' => 0,
			'_r' => 255,
			'_g' => 255,
			'_b' => 255,
		),
		'fontFamily' => 'Arial',
		'menuAnimation' => true,
		'multiPageHeightCount' => 2,
		'multiPageWidthCount' => 2,
		'printDestination' => 0,
		'showAboutButton' => true,
		'showBookmarksButton' => true,
		'showButtonCaptions' => true,
		'showCurrentPageControl' => true,
		'showDesignButton' => false,
		'showEditorButton' => true,
		'showFindButton' => true,
		'showFirstPageButton' => true,
		'showFullScreenButton' => true,
		'showLastPageButton' => true,
		'showMenuMode' => 0,
		'showNextPageButton' => true,
		'showOpenButton' => true,
		'showParametersButton' => true,
		'showPinToolbarButton' => true,
		'showPreviousPageButton' => true,
		'showPrintButton' => true,
		'showRefreshButton' => true,
		'showResourcesButton' => true,
		'showSaveButton' => true,
		'showSendEmailButton' => false,
		'showViewModeButton' => true,
		'showZoomButton' => true,
		'viewMode' => 0,
		'visible' => true,
	);
}
